#!/bin/sh
# Copyright (C) 2017 Gregory L. Dietsche
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License version 2 as published by the
# Free Software Foundation. This program is distributed in the hope that it
# will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# You should have received a copy of the GNU General Public License along with
# this program. If not, see http://www.gnu.org/licenses/.
. /lib/functions.sh
. /lib/genesis39-run-once.sh

uci -q batch <<-EOT
  set network.wan.peerdns='0'
  set network.wan6.peerdns='0'

  #DO NOT Allow upstream responses in the 127.0.0.0/8 range, e.g. for RBL services
  delete dhcp.@dnsmasq[0].rebind_localhost

  delete dhcp.@dnsmasq[0].server
  add_list dhcp.@dnsmasq[0].server=208.67.222.123
  add_list dhcp.@dnsmasq[0].server=208.67.220.123

  set ddns.myddns_ipv4.service_name='dnsomatic.com'
EOT

ip=$(uci get network.lan.ipaddr)
rule=$(uci add firewall redirect)
uci -q batch <<-EOT
  set firewall.$rule.target='DNAT'
  set firewall.$rule.src='lan'
  set firewall.$rule.proto='tcpudp'
  set firewall.$rule.src_dport='53'
  set firewall.$rule.dest='lan'
  set firewall.$rule.dest_ip='$ip'
  set firewall.$rule.name='redirect all lan dns requests to this router'
EOT

ip=$(uci get network.Guest.ipaddr)
rule=$(uci add firewall redirect)
uci -q batch <<-EOT
  set firewall.$rule.target='DNAT'
  set firewall.$rule.src='Guest'
  set firewall.$rule.proto='tcpudp'
  set firewall.$rule.src_dport='53'
  set firewall.$rule.dest='Guest'
  set firewall.$rule.dest_ip='$ip'
  set firewall.$rule.name='redirect all Guest dns requests to this router'
EOT

uci commit

