#!/bin/bash
# Copyright (C) 2017 Gregory L. Dietsche
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License version 2 as published by the
# Free Software Foundation. This program is distributed in the hope that it
# will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# You should have received a copy of the GNU General Public License along with
# this program. If not, see http://www.gnu.org/licenses/.

uci -q batch <<-EOT
  set network.guest=interface
  set network.guest.type='bridge'
  set network.guest.proto='static'
  set network.guest.ipaddr='192.168.2.1'
  set network.guest.netmask='255.255.255.0'
EOT

uci -q batch <<-EOT
  set dhcp.guest=dhcp
  set dhcp.guest.start='50'
  set dhcp.guest.leasetime='6h'
  set dhcp.guest.limit='200'
  set dhcp.guest.interface='guest'
EOT

iface=$(uci add wireless wifi-iface)
uci -q batch <<-EOT
  set wireless.$iface.device='radio0'
  set wireless.$iface.mode='ap'
  set wireless.$iface.ssid='Genesis39-Guest'
  set wireless.$iface.encryption='psk2'
  set wireless.$iface.network='guest'
  set wireless.$iface.isolate='1'
EOT

iface=$(uci add wireless wifi-iface)
uci -q batch <<-EOT
  set wireless.$iface.device='radio1'
  set wireless.$iface.mode='ap'
  set wireless.$iface.ssid='Genesis39-Guest'
  set wireless.$iface.encryption='psk2'
  set wireless.$iface.network='guest'
  set wireless.$iface.isolate='1'
EOT


rule=$(uci add firewall zone)
uci -q batch <<-EOT
  set firewall.$rule.input='ACCEPT'
  set firewall.$rule.forward='REJECT'
  set firewall.$rule.output='ACCEPT'
  set firewall.$rule.name='guest'
  set firewall.$rule.network='guest'
EOT

rule=$(uci add firewall forwarding)
uci -q batch <<-EOT
  set firewall.$rule.src='guest'
  set firewall.$rule.dest='wan'
EOT

rule=$(uci add firewall rule)
uci -q batch <<-EOT
  set firewall.$rule.enabled='1'
  set firewall.$rule.src='guest'
  set firewall.$rule.dest_port='80'
  set firewall.$rule.target='DROP'
  set firewall.$rule.name='guest-no-webui-http'
EOT

rule=$(uci add firewall rule)
uci -q batch <<-EOT
  set firewall.$rule.enabled='1'
  set firewall.$rule.src='guest'
  set firewall.$rule.dest_port='443'
  set firewall.$rule.target='DROP'
  set firewall.$rule.name='guest-no-webui-https'
EOT

rule=$(uci add firewall rule)
uci -q batch <<-EOT
  set firewall.$rule.enabled='1'
  set firewall.$rule.src='guest'
  set firewall.$rule.dest_port='22'
  set firewall.$rule.target='DROP'
  set firewall.$rule.name='guest-no-ssh-management'
EOT

uci commit
