#!/bin/sh
# Copyright (C) 2017 Gregory L. Dietsche
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License version 2 as published by the
# Free Software Foundation. This program is distributed in the hope that it
# will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# You should have received a copy of the GNU General Public License along with
# this program. If not, see http://www.gnu.org/licenses/.
. /lib/functions.sh

ip=$(uci get network.lan.ipaddr)
rule=$(uci add firewall redirect)
uci -q batch <<-EOT
  set firewall.$rule.target='DNAT'
  set firewall.$rule.src='lan'
  set firewall.$rule.proto='udp'
  set firewall.$rule.src_dport='123'
  set firewall.$rule.dest='lan'
  set firewall.$rule.dest_ip='$ip'
  set firewall.$rule.name='redirect all lan ntp requests to this router'
EOT
