#!/bin/sh
# Copyright (C) 2017 Gregory L. Dietsche
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License version 2 as published by the
# Free Software Foundation. This program is distributed in the hope that it
# will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# You should have received a copy of the GNU General Public License along with
# this program. If not, see http://www.gnu.org/licenses/.
. /lib/functions.sh

set_ssid() {
  uci -q batch <<-EOT
  set wireless.$1.ssid='Genesis39'
EOT
}

enable_wifi() {
  uci -q batch <<-EOT
  set wireless.$1.disabled=0
EOT
}

config_load wireless
config_foreach enable_wifi wifi-device
config_foreach set_ssid wifi-iface

uci commit
