#!/bin/sh
# Copyright (C) 2017 Gregory L. Dietsche
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License version 2 as published by the
# Free Software Foundation. This program is distributed in the hope that it
# will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# You should have received a copy of the GNU General Public License along with
# this program. If not, see http://www.gnu.org/licenses/.

cat <<EOT >> /etc/firewall.user
echo "   * Genesis 39: Reroute all LAN DNS requests to this router"
iptables -t nat -A PREROUTING -s 192.168.1.0/24 -p udp --dport 53 -j DNAT --to 192.168.1.1
iptables -t nat -A PREROUTING -s 192.168.1.0/24 -p tcp --dport 53 -j DNAT --to 192.168.1.1

echo "   * Genesis 39: Reroute all Guest DNS requests to this router"
iptables -t nat -A PREROUTING -s 192.168.2.0/24 -p udp --dport 53 -j DNAT --to 192.168.2.1
iptables -t nat -A PREROUTING -s 192.168.2.0/24 -p tcp --dport 53 -j DNAT --to 192.168.2.1

EOT

uci -q batch <<-EOT
  set network.wan.peerdns='0'
  set network.wan6.peerdns='0'

  #DO NOT Allow upstream responses in the 127.0.0.0/8 range, e.g. for RBL services
  delete dhcp.@dnsmasq[0].rebind_localhost

  delete dhcp.@dnsmasq[0].server
  add_list dhcp.@dnsmasq[0].server=208.67.222.123
  add_list dhcp.@dnsmasq[0].server=208.67.220.123

  set ddns.myddns_ipv4.service_name='opendns.com'
EOT

uci commit

