#!/bin/sh
# Copyright (C) 2017 Gregory L. Dietsche
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License version 2 as published by the
# Free Software Foundation. This program is distributed in the hope that it
# will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# You should have received a copy of the GNU General Public License along with
# this program. If not, see http://www.gnu.org/licenses/.
. /lib/functions.sh
. /lib/genesis39-run-once.sh

wifi_enable() {
  uci -q batch <<-EOT
  delete wireless.$1.disabled
EOT
}

config_load wireless
config_foreach wifi_enable wifi-device
