#!/bin/bash
# Copyright (C) 2017 Gregory L. Dietsche
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License version 2 as published by the
# Free Software Foundation. This program is distributed in the hope that it
# will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# You should have received a copy of the GNU General Public License along with
# this program. If not, see http://www.gnu.org/licenses/.

uci -q batch <<-EOT
  set network.guest=interface
  set network.guest.type='bridge'
  set network.guest.proto='static'
  set network.guest.ipaddr='192.168.2.1'
  set network.guest.netmask='255.255.255.0'

  set wireless.@wifi-iface[2]=wifi-iface
  set wireless.@wifi-iface[2].device='radio0'
  set wireless.@wifi-iface[2].mode='ap'
  set wireless.@wifi-iface[2].ssid='Genesis39-Guest'
  set wireless.@wifi-iface[2].encryption='psk2'
  set wireless.@wifi-iface[2].network='guest'
  set wireless.@wifi-iface[2].isolate='1'

  set wireless.@wifi-iface[3]=wifi-iface
  set wireless.@wifi-iface[3].device='radio1'
  set wireless.@wifi-iface[3].mode='ap'
  set wireless.@wifi-iface[3].ssid='Genesis39-Guest'
  set wireless.@wifi-iface[3].encryption='psk-mixed'
  set wireless.@wifi-iface[3].network='guest'
  set wireless.@wifi-iface[3].isolate='1'

  set dhcp.guest=dhcp
  set dhcp.guest.start='50'
  set dhcp.guest.leasetime='12h'
  set dhcp.guest.limit='200'
  set dhcp.guest.interface='guest'

#only accept output
  set firewall.@zone[2]=zone
  set firewall.@zone[2].input='ACCEPT'
  set firewall.@zone[2].forward='REJECT'
  set firewall.@zone[2].output='ACCEPT'
  set firewall.@zone[2].name='guest'
  set firewall.@zone[2].network='guest'

  set firewall.@forwarding[1]=forwarding
  set firewall.@forwarding[1].dest='wan'
  set firewall.@forwarding[1].src='guest'
  set firewall.@forwarding[2]=forwarding
  set firewall.@forwarding[2].dest='guest'
  set firewall.@forwarding[2].src='wan'

  set firewall.@rule[9]=rule
  set firewall.@rule[9].enabled='1'
  set firewall.@rule[9].src='guest'
  set firewall.@rule[9].dest_port='80'
  set firewall.@rule[9].target='DROP'
  set firewall.@rule[9].name='guest-no-webui-http'

  set firewall.@rule[10]=rule
  set firewall.@rule[10].enabled='1'
  set firewall.@rule[10].src='guest'
  set firewall.@rule[10].dest_port='443'
  set firewall.@rule[10].target='DROP'
  set firewall.@rule[10].name='guest-no-webui-https'

  set firewall.@rule[11]=rule
  set firewall.@rule[11].enabled='1'
  set firewall.@rule[11].src='guest'
  set firewall.@rule[11].dest_port='22'
  set firewall.@rule[11].target='DROP'
  set firewall.@rule[11].name='guest-no-ssh-management'

EOT

uci commit
