#!/bin/sh
# Copyright (C) 2017 Gregory L. Dietsche
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License version 2 as published by the
# Free Software Foundation. This program is distributed in the hope that it
# will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# You should have received a copy of the GNU General Public License along with
# this program. If not, see http://www.gnu.org/licenses/.
. /lib/functions.sh
. /lib/genesis39-run-once.sh
. /lib/genesis39-functions.sh

network=Guest
zonename=Guest
wifiname='Genesis39-Guest'
wifikey='Genesis39'
wifiencryption='none'
ip='192.168.12.1'

genesis39_add_network $network $ip
genesis39_add_zone $zonename $network
genesis39_allow_zone_ntp_to_router $zonename
genesis39_force_zone_ntp_to_router $zonename $network

wifi_addGuest() {
  local iface=$(uci add wireless wifi-iface)
  uci -q batch <<-EOT
    set wireless.$iface.device='$1'
    set wireless.$iface.mode='ap'
    set wireless.$iface.ssid='$wifiname'
    set wireless.$iface.key='$wifikey'
    set wireless.$iface.encryption='$wifiencryption'
    set wireless.$iface.network=$network
    set wireless.$iface.isolate='1'
EOT
}

config_load wireless
config_foreach wifi_addGuest wifi-device
