#!/bin/sh
# Copyright (C) 2017 Gregory L. Dietsche
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License version 2 as published by the
# Free Software Foundation. This program is distributed in the hope that it
# will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# You should have received a copy of the GNU General Public License along with
# this program. If not, see http://www.gnu.org/licenses/.
. /lib/functions.sh
. /lib/genesis39-run-once.sh
. /lib/genesis39-functions.sh

#
# Same trick that we did with DNS
#
# The router will answer all NTP requests even when a NTP client tries
# to communicate with a different NTP server on the internet.
#
# This has the fun side-effect of making every host on the internet look
# like it is running a NTP server!
#
genesis39_force_zone_ntp_to_router lan lan
