#!/bin/sh
# Copyright (C) 2017 Gregory L. Dietsche
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License version 2 as published by the
# Free Software Foundation. This program is distributed in the hope that it
# will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# You should have received a copy of the GNU General Public License along with
# this program. If not, see http://www.gnu.org/licenses/.
. /lib/functions.sh
. /lib/genesis39-run-once.sh
. /lib/genesis39-functions.sh

networkname=Guest
zonename=Guest
wifiname='Genesis39-Guest'
wifikey='Genesis39'
ip='192.168.11.1'

wifi_addGuest() {
  iface=$(uci add wireless wifi-iface)
  uci -q batch <<-EOT
    set wireless.$iface.device='$1'
    set wireless.$iface.mode='ap'
    set wireless.$iface.ssid='$wifiname'
    set wireless.$iface.key='$wifikey'
    set wireless.$iface.encryption='psk2'
    set wireless.$iface.network=$netname
    set wireless.$iface.isolate='1'

    set wireless.$iface.wps_device_name="Genesis39 AP"
    set wireless.$iface.wps_manufacturer="Genesis39.org"
    set wireless.$iface.wps_pushbutton='1'
EOT
}

config_load wireless
config_foreach wifi_addGuest wifi-device

uci -q batch <<-EOT
  set network.$netname=interface
  set network.$netname.type='bridge'
  set network.$netname.proto='static'
  set network.$netname.ipaddr='$ip'
  set network.$netname.netmask='255.255.255.0'
EOT

uci -q batch <<-EOT
  set dhcp.$netname=dhcp
  set dhcp.$netname.start='50'
  set dhcp.$netname.leasetime='6h'
  set dhcp.$netname.limit='200'
  set dhcp.$netname.interface=$netname
EOT

uci -q batch <<-EOT
  set dhcp.$netname.ra='server'
  set dhcp.$netname.dhcpv6='server'
EOT

genesis39_add_zone $zonename $networkname
genesis39_force_zone_ntp_to_router $zonename
