#!/bin/sh
# Copyright (C) 2017 Gregory L. Dietsche
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License version 2 as published by the
# Free Software Foundation. This program is distributed in the hope that it
# will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# You should have received a copy of the GNU General Public License along with
# this program. If not, see http://www.gnu.org/licenses/.
. /lib/functions.sh
. /lib/genesis39-run-once.sh

uci -q batch <<-EOT
  set system.@system[0].hostname='Genesis39'

  set luci.diag.dns='Genesis39.org'
  set luci.diag.ping='Genesis39.org'
  set luci.diag.route='Genesis39.org'
EOT

wifi_ssid() {
  uci -q batch <<-EOT
  set wireless.$1.ssid='Genesis39'
  set wireless.$1.encryption='psk2'
  set wireless.$1.key='!Genesis39'
EOT
}

config_load wireless
config_foreach wifi_ssid wifi-iface
