#!/bin/sh
# Copyright (C) 2017 Gregory L. Dietsche
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License version 2 as published by the
# Free Software Foundation. This program is distributed in the hope that it
# will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# You should have received a copy of the GNU General Public License along with
# this program. If not, see http://www.gnu.org/licenses/.
. /lib/functions.sh
. /lib/genesis39-run-once.sh
. /lib/genesis39-functions.sh

#extra isn't an openwrt/lede option.
#we use it so that it's easy to "turn it off" later
addCNAME() {
  rule=$(uci add dhcp cname)
  uci -q batch <<-EOT
  set dhcp.$rule.cname=$1
  set dhcp.$rule.target=$2,$3
EOT
}

uci add_list dhcp.@dnsmasq[0].addnhosts=/etc/hosts.safesearch.google
addCNAME google.com,www.google.com forcesafesearch.google.com 86400

uci add_list dhcp.@dnsmasq[0].addnhosts=/etc/hosts.safesearch.bing
addCNAME www.bing.com strict.bing.com 86400
