#!/bin/sh
# Copyright (C) 2017 Gregory L. Dietsche
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License version 2 as published by the
# Free Software Foundation. This program is distributed in the hope that it
# will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# You should have received a copy of the GNU General Public License along with
# this program. If not, see http://www.gnu.org/licenses/.
. /lib/functions.sh
. /lib/genesis39-run-once.sh
. /lib/genesis39-functions.sh

uci -q batch <<-EOT
  set network.wan.peerdns='0'
  set network.wan6.peerdns='0'

  #DO NOT Allow upstream responses in the 127.0.0.0/8 range, e.g. for RBL services
  delete dhcp.@dnsmasq[0].rebind_localhost

  set ddns.myddns_ipv4.service_name='dnsomatic.com'
EOT

if command -v dnscrypt-proxy; then
  uci -q batch <<-EOT
    delete dhcp.@dnsmasq[0].server
    add_list dhcp.@dnsmasq[0].server='127.0.0.1#5353'
    add_list dhcp.@dnsmasq[0].server='/pool.ntp.org/8.8.8.8'
    add_list dhcp.@dnsmasq[0].server='/openwrt.org/8.8.8.8'
    add_list dhcp.@dnsmasq[0].server='/downloads.openwrt.org/8.8.8.8'

    set dnscrypt-proxy.ns1.resolver='cleanbrowsing-adult'
EOT
else
  uci -q batch <<-EOT
    delete dhcp.@dnsmasq[0].server
    add_list dhcp.@dnsmasq[0].server=185.228.168.10
    add_list dhcp.@dnsmasq[0].server=185.228.169.11
EOT
fi

genesis39_force_zone_dns_to_router lan
genesis39_force_zone_dns_to_router Guest
